# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Ciara's Textbook
author: Ciara Acosta
logo: flowers.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/CiaraAcosta/example-textbook
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
